---
title       : Interactive Visualizations
subtitle    : rCharts, UseR 2014
author      : Ramnath Vaidyanathan (@ramnath_vaidya)
job         : McGill University
--- .nobackground .quote

<q>rCharts is an R package to create, customize and share interactive visualizations by leveraging javascript libraries.</q>

--- #rchartssite

```{r echo = F, cache = F}
library(rMaps); library(rCharts)
source('data/map_specs.R')
world_map = map_world(geo = list(url = 'world.topo.json'))
```

--- &interactive2 height:100

<a class='example'>NVD3</a>

```{r, opts.label = 'interactive', results = 'asis'}
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == 'Male')
library(rCharts)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', data = hair_eye_male, type = 'multiBarChart')
n1
```

--- &interactive2 height:100

<a class='example'>NVD3</a>

```{r, opts.label = 'interactive', results = 'asis'}
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == 'Male')
library(rCharts)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', data = hair_eye_male, type = 'multiBarChart')
n1$chart(color = c('brown', 'blue', '#594c26', 'green'))
n1
```

--- &interactive2 height:40

<a class='example'>DataTable</a>

```{r opts.label = 'interactive', results = 'asis'}
library(rCharts)
dTable(MASS::survey)
```



--- .segue .nobackground

## Thank You



<style>iframe.uvcharts{height: 600px;}</style>



